apiVersion: v1
kind: Pod
metadata:
  name: apache-log
  namespace: web
  labels:
    app: apache-log
spec:
  containers:
  - name: apache-log
    image: digitalkali/apache-logs
    imagePullPolicy: Always
    env:
    - name: FLAG
      value: "ALL_YOUR_BASE_ARE_BELONG_TO_US"
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "300m"
        
