apiVersion: v1
kind: Pod
metadata:
  name: apache-log
  namespace: web
  labels:
    app: apache-log
spec:
  nodeSelector:
    worker: "true"
  containers:
  - name: apache-log
    image: digitalkali/apache-logs:latest
    imagePullPolicy: Always
    securityContext:
      privileged: false
      runAsUser:
        rule: MustRunAsNonRoot
      allowPrivilegeEscalation: false
      runAsUser: 10500
      runAsGroup: 10500
      capabilities:
        drop:
        - "ALL"
        add:
        - "NET_ADMIN"
        - "SYS_TIME"
    env:
    - name: FLAG
      value: "ALL_YOUR_BASE_ARE_BELONG_TO_US"
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "300m"
        
