# https://github.com/digitalkali/apache-logs
# kubectl apply -f ./deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-log
spec:
  selector:
      matchLabels:
        app: apache-log
  replicas: 1
  template:
      metadata:
        labels:
            app: apache-log
      spec:
        containers:
        - name: apache-log
          image: digitalkali/apache-logs
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
